#ifndef ADAU1467_H
#define ADAU1467_H
#include <string>
#include "linux/spi/spidev.h"
#include <sys/ioctl.h>
#include <fcntl.h>
#include <QString>
//#include <iGate4CH_DSP/selfbootdata.h>
#include <DesignDSP_REC_V1/DesignDSP_REC_V1_IC_1_PARAM.h>
#include <SPI.h>

#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
#define WRITE 0
#define READ 1
#define DSPDATABUF 4096 // 4096

typedef unsigned short ADI_DATA_U16;
typedef unsigned char ADI_REG_TYPE;
typedef unsigned char byte;
/*
 * Parameter data format
 */
#define SIGMASTUDIOTYPE_FIXPOINT 0
#define SIGMASTUDIOTYPE_INTEGER  1

#define DSP_TYPE_SIGMA300_350 3    // Sigma300/Sigma350: ADAU145x, ADAU146x

// Which type of DSP is connected?
#define DSP_TYPE DSP_TYPE_SIGMA300_350


// For compatibility with certain export files, redirect SIGMASTUDIOTYPE_8_24_CONVERT to
// SIGMASTUDIOTYPE_FIXPOINT_CONVERT
#define SIGMASTUDIOTYPE_8_24_CONVERT(x) ADAU1467::SIGMASTUDIOTYPE_FIXPOINT_CONVERT(x)
// Separate a 32-bit floating point value into four bytes



#define AUDIOIN_VOLUME_CH1_ADDRESS MOD_SPLT1_ALG0_STAGE0_MULTICTRLSPLITTERS300SLEW2TARGET0_ADDR
#define SIDETONE_VOLUME_CH1_ADDRESS MOD_SPLT1_ALG0_STAGE1_MULTICTRLSPLITTERS300SLEW2TARGET1_ADDR
#define SIDETONE_VOLUME_CH1_MODE_ADDRESS MOD_SPLT1_ALG0_SLEW_MODE_ADDR
#define SIDETONE_VOLUME_CH1_MODE_VALUE MOD_SPLT1_ALG0_SLEW_MODE_FIXPT

#define AUDIOIN_VOLUME_CH2_ADDRESS MOD_SPLT2_ALG0_STAGE0_MULTICTRLSPLITTERS300SLEW1TARGET0_ADDR
#define SIDETONE_VOLUME_CH2_ADDRESS MOD_SPLT2_ALG0_STAGE1_MULTICTRLSPLITTERS300SLEW1TARGET1_ADDR
#define SIDETONE_VOLUME_CH2_MODE_ADDRESS MOD_SPLT2_ALG0_SLEW_MODE_ADDR
#define SIDETONE_VOLUME_CH2_MODE_VALUE MOD_SPLT2_ALG0_SLEW_MODE_FIXPT

#define AUDIOIN_VOLUME_CH3_ADDRESS MOD_SPLT3_ALG0_STAGE0_MULTICTRLSPLITTERS300SLEW3TARGET0_ADDR
#define SIDETONE_VOLUME_CH3_ADDRESS MOD_SPLT3_ALG0_STAGE1_MULTICTRLSPLITTERS300SLEW3TARGET1_ADDR
#define SIDETONE_VOLUME_CH3_MODE_ADDRESS MOD_SPLT3_ALG0_SLEW_MODE_ADDR
#define SIDETONE_VOLUME_CH3_MODE_VALUE MOD_SPLT3_ALG0_SLEW_MODE_FIXPT

#define AUDIOIN_VOLUME_CH4_ADDRESS MOD_SPLT4_ALG0_STAGE0_MULTICTRLSPLITTERS300SLEW4TARGET0_ADDR
#define SIDETONE_VOLUME_CH4_ADDRESS MOD_SPLT4_ALG0_STAGE1_MULTICTRLSPLITTERS300SLEW4TARGET1_ADDR
#define SIDETONE_VOLUME_CH4_MODE_ADDRESS MOD_SPLT4_ALG0_SLEW_MODE_ADDR
#define SIDETONE_VOLUME_CH4_MODE_VALUE MOD_SPLT4_ALG0_SLEW_MODE_FIXPT

#define AUDIOOUT_VOLUME_CH1_TARGET_ADDR MOD_SINGLE1_ALG0_TARGET_ADDR
#define AUDIOOUT_VOLUME_CH1_MOD_ADDR MOD_SINGLE1_ALG0_SLEW_MODE_ADDR
#define AUDIOOUT_VOLUME_CH1_MOD_VALUE MOD_SINGLE1_ALG0_SLEW_MODE_FIXPT

#define AUDIOOUT_VOLUME_CH2_TARGET_ADDR MOD_SINGLE2_ALG0_TARGET_ADDR
#define AUDIOOUT_VOLUME_CH2_MOD_ADDR MOD_SINGLE2_ALG0_SLEW_MODE_ADDR
#define AUDIOOUT_VOLUME_CH2_MOD_VALUE MOD_SINGLE2_ALG0_SLEW_MODE_FIXPT

#define AUDIOOUT_VOLUME_CH3_TARGET_ADDR MOD_SINGLE3_ALG0_TARGET_ADDR
#define AUDIOOUT_VOLUME_CH3_MOD_ADDR MOD_SINGLE3_ALG0_SLEW_MODE_ADDR
#define AUDIOOUT_VOLUME_CH3_MOD_VALUE MOD_SINGLE3_ALG0_SLEW_MODE_FIXPT

#define AUDIOOUT_VOLUME_CH4_TARGET_ADDR MOD_SINGLE4_ALG0_TARGET_ADDR
#define AUDIOOUT_VOLUME_CH4_MOD_ADDR MOD_SINGLE4_ALG0_SLEW_MODE_ADDR
#define AUDIOOUT_VOLUME_CH4_MOD_VALUE MOD_SINGLE4_ALG0_SLEW_MODE_FIXPT

// TONE define
#define TONE_CH1_ADDRESS MOD_TONE1_ALG0_SINEPHASEGAINALGS3001GAIN00_ADDR
#define TONE_LEVEL_CH1_ADDRESS MOD_TONE1_ALG0_SINEPHASEGAINALGS3001GAIN00_ADDR
#define TONE_PHASE_CH1_ADDRESS MOD_TONE1_ALG0_SINEPHASEGAINALGS3001INDEXFPHI00_ADDR
#define TONE_FREQUENCY_CH1_ADDRESS MOD_TONE1_ALG0_INCREMENT_ADDR

#define TONE_CH2_ADDRESS MOD_TONE1_2_ALG0_SINEPHASEGAINALGS3002GAIN00_ADDR
#define TONE_LEVEL_CH2_ADDRESS MOD_TONE1_2_ALG0_SINEPHASEGAINALGS3002GAIN00_ADDR
#define TONE_PHASE_CH2_ADDRESS MOD_TONE1_2_ALG0_SINEPHASEGAINALGS3002INDEXFPHI00_ADDR
#define TONE_FREQUENCY_CH2_ADDRESS MOD_TONE1_2_ALG0_INCREMENT_ADDR

#define TONE_CH3_ADDRESS MOD_TONE1_3_ALG0_SINEPHASEGAINALGS3003GAIN00_ADDR
#define TONE_LEVEL_CH3_ADDRESS MOD_TONE1_3_ALG0_SINEPHASEGAINALGS3003GAIN00_ADDR
#define TONE_PHASE_CH3_ADDRESS MOD_TONE1_3_ALG0_SINEPHASEGAINALGS3003INDEXFPHI00_ADDR
#define TONE_FREQUENCY_CH3_ADDRESS MOD_TONE1_3_ALG0_INCREMENT_ADDR

#define TONE_CH4_ADDRESS MOD_TONE1_4_ALG0_SINEPHASEGAINALGS3004GAIN00_ADDR
#define TONE_LEVEL_CH4_ADDRESS MOD_TONE1_4_ALG0_SINEPHASEGAINALGS3004GAIN00_ADDR
#define TONE_PHASE_CH4_ADDRESS MOD_TONE1_4_ALG0_SINEPHASEGAINALGS3004INDEXFPHI00_ADDR
#define TONE_FREQUENCY_CH4_ADDRESS MOD_TONE1_4_ALG0_INCREMENT_ADDR

// TONE SERVSR
#define TONE_SERVER_CH1_ADDRESS MOD_TONE1_5_ALG0_SINEPHASEGAINALGS3006GAIN00_ADDR
#define TONE_SERVER_LEVEL_CH1_ADDRESS MOD_TONE1_5_ALG0_SINEPHASEGAINALGS3006GAIN00_ADDR
#define TONE_SERVER_PHASE_CH1_ADDRESS MOD_TONE1_5_ALG0_SINEPHASEGAINALGS3006INDEXFPHI00_ADDR
#define TONE_SERVER_FREQUENCY_CH1_ADDRESS MOD_TONE1_5_ALG0_INCREMENT_ADDR

#define TONE_SERVER_CH2_ADDRESS MOD_TONE1_6_ALG0_SINEPHASEGAINALGS3007GAIN00_ADDR
#define TONE_SERVER_LEVEL_CH2_ADDRESS MOD_TONE1_6_ALG0_SINEPHASEGAINALGS3007GAIN00_ADDR
#define TONE_SERVER_PHASE_CH2_ADDRESS MOD_TONE1_6_ALG0_SINEPHASEGAINALGS3007INDEXFPHI00_ADDR
#define TONE_SERVER_FREQUENCY_CH2_ADDRESS MOD_TONE1_6_ALG0_INCREMENT_ADDR

#define TONE_SERVER_CH3_ADDRESS MOD_TONE1_7_ALG0_SINEPHASEGAINALGS3008GAIN00_ADDR
#define TONE_SERVER_LEVEL_CH3_ADDRESS MOD_TONE1_7_ALG0_SINEPHASEGAINALGS3008GAIN00_ADDR
#define TONE_SERVER_PHASE_CH3_ADDRESS MOD_TONE1_7_ALG0_SINEPHASEGAINALGS3008INDEXFPHI00_ADDR
#define TONE_SERVER_FREQUENCY_CH3_ADDRESS MOD_TONE1_7_ALG0_INCREMENT_ADDR

#define TONE_SERVER_CH4_ADDRESS MOD_TONE1_8_ALG0_SINEPHASEGAINALGS3005GAIN00_ADDR
#define TONE_SERVER_LEVEL_CH4_ADDRESS MOD_TONE1_8_ALG0_SINEPHASEGAINALGS3005GAIN00_ADDR
#define TONE_SERVER_PHASE_CH4_ADDRESS MOD_TONE1_8_ALG0_SINEPHASEGAINALGS3005INDEXFPHI00_ADDR
#define TONE_SERVER_FREQUENCY_CH4_ADDRESS MOD_TONE1_8_ALG0_INCREMENT_ADDR

#define REC_IN_LEVEL_CH1_ADDR MOD_SPILTER_REC_1_ALG0_STAGE1_MULTICTRLSPLITTERS3001GAIN1_ADDR
#define REC_IN_LEVEL_CH2_ADDR MOD_SPILTER_REC_2_ALG0_STAGE1_MULTICTRLSPLITTERS3002GAIN1_ADDR
#define REC_IN_LEVEL_CH3_ADDR MOD_SPILTER_REC_3_ALG0_STAGE1_MULTICTRLSPLITTERS3003GAIN1_ADDR
#define REC_IN_LEVEL_CH4_ADDR MOD_SPILTER_REC_4_ALG0_STAGE1_MULTICTRLSPLITTERS3004GAIN1_ADDR

#define REC_OUT_LEVEL_CH1_ADDR MOD_ROIPOUT_SPILTER_REC_1_ALG0_STAGE0_MULTICTRLSPLITTERS3005GAIN0_ADDR
#define REC_OUT_LEVEL_CH2_ADDR MOD_ROIPOUT_SPILTER_REC_2_ALG0_STAGE0_MULTICTRLSPLITTERS3006GAIN0_ADDR
#define REC_OUT_LEVEL_CH3_ADDR MOD_ROIPOUT_SPILTER_REC_3_ALG0_STAGE0_MULTICTRLSPLITTERS3007GAIN0_ADDR
#define REC_OUT_LEVEL_CH4_ADDR MOD_ROIPOUT_SPILTER_REC_4_ALG0_STAGE0_MULTICTRLSPLITTERS3008GAIN0_ADDR


class ADAU1467
{
public:
    explicit ADAU1467(const std::string& spidev);

    /*
     * Convert a floating-point value to SigmaDSP (5.23 or 8.24) fixed point format
     */
    #if DSP_TYPE == DSP_TYPE_SIGMA300_350
    int32_t SIGMASTUDIOTYPE_FIXPOINT_CONVERT(double value) { return int32_t(value * (0x01 << 24)); }
    #else
    int32_t SIGMASTUDIOTYPE_FIXPOINT_CONVERT(double value) { return int32_t(value * (0x01 << 23)) & 0xFFFFFFF; }
    #endif

    // Separate a 32-bit floating point value into four bytes
    void SIGMASTUDIOTYPE_REGISTER_CONVERT(int32_t fixpt_val, byte dest[4]);
    void SIGMASTUDIOTYPE_INTEGER_CONVERT(int32_t fixpt_val, byte dest[4]);
    void SIGMA_WRITE_REGISTER_BLOCK(byte devAddress, int address, int length, byte pData[]);
    void SIGMA_WRITE_REGISTER_BLOCK(int address, int length, byte pData[]);
    void SIGMA_WRITE_REGISTER_INTEGER(int address, int32_t pData);
    void SIGMA_WRITE_REGISTER_FLOAT(int address, double pData);
    void SIGMA_WRITE_DELAY(byte devAddress, int length, byte pData[]);
    void SIGMA_READ_REGISTER_BYTES(uint16_t address, int length, byte *pData);
    uint32_t SIGMA_READ_REGISTER_INTEGER(uint16_t address, int length);
    double SIGMA_READ_REGISTER_FLOAT(int address);
    void SIGMA_PRINT_REGISTER(int address, int dataLength);
    void default_download_IC_1();
    void WriteSelfBootMemoryToDSP();

    void setMixerVolume(uint16_t address, uint16_t modeAddress, uint32_t modeValue, double value);
    void setModuleSingleVolume(uint16_t targetAddress, uint16_t slewModeAddress, uint32_t modeValue, double value);
    //TONE
    void setToneVolume(uint16_t address, double value);

    void setFIRfilter(int fir_start_addr, int fir_filter_length, double* coefficients);

    void setDSPSplitVolume(uint16_t address, double value);
private:
    void saveLoadWrite0x6000(double dValue);
    void blokcWrite(uint16_t address);
    void blokcWrite(uint16_t modeAddress, uint32_t modeValue);


//    void spi_init();
    bool send_byte_data(uint8_t const *byteData, uint32_t len);
    void transfer(int fd, uint8_t const *tx, uint8_t const *rx, size_t len);
//    int mode_spi=0;
//    int ret_spi=0;
//    int fd_spi;
//    uint8_t bits = 8;
//    uint32_t speed = 500000;
//    uint16_t delay = 100;
    uint8_t tx_tmp[DSPDATABUF];
    uint8_t tx[DSPDATABUF];
    uint8_t rx[ARRAY_SIZE(tx)] = {0, };

    SPIClass *DSPSPI;
    std::string spiDev;

};

#endif // ADAU1467_H
